# Source language and JDK version to use
language: java
jdk: oraclejdk8

# Compile and package JAR and set build properties
install: gradlew setupCIWorkspace
script: gradlew build -PbuildNumber=$TRAVIS_BUILD_NUMBER -PciSystem=travis -Pcommit=${TRAVIS_COMMIT:0:7}

# Perform steps after compilation/test success
after_success:
  # Check if commit s not a pull request, if git repo is official, and if branch is 1.7. If checks pass, add libs and deploy artifacts to Maven repository.
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == Ordinastie/MalisisCore ]] && [[ $TRAVIS_BRANCH == 1.8.9]] && ./gradlew uploadArchives"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Super secure, encrypted variables! Ssssh!
    - secure: eLRcYXZuIG57lRbCtCIVw9nvLYntFyt6sTSJtjHWD1qa8xaJScHVvBBMZ2iga6KnFwgALNkhCqXpjVzabY0okr2ehf0XhIIQbD91ei2xY/d3WuivtkrD1ECjOaDQCnLMBsNJ/jfydV0vRePXaSL/f/5nZY7xa5evrPpEjhBn36U=
    - secure: J3MwV09XmvNw3nUfKrV7/FnPqgRnv/rsC6LFnNh10+ExT/xXCtRW4K9B05ET8gmw8z2c3xvA3GklFMfNqJYE+WigrBqd0lFuZWsYbnuz0azeczQuc7ps8UL7NPxNLDFiqJMc8QdEodW6GOXptYbUFerlVQW4iPHck+WKtplUEUw=
